OnlineNewspaper/OnlineNewspaper/Controllers/NewsCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineNewspaper.Data;
using OnlineNewspaper.Models;

namespace OnlineNewspaper.Controllers
{
    public class NewsCategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NewsCategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: NewsCategories
        public async Task<IActionResult> Index()
        {
            return View(await _context.NewsCategory.ToListAsync());
        }

        // GET: NewsCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsCategory = await _context.NewsCategory
                .FirstOrDefaultAsync(m => m.NewsCategoryID == id);
            if (newsCategory == null)
            {
                return NotFound();
            }

            return View(newsCategory);
        }

        // GET: NewsCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NewsCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NewsCategoryID,Name")] NewsCategory newsCategory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(newsCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(newsCategory);
        }

        // GET: NewsCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsCategory = await _context.NewsCategory.FindAsync(id);
            if (newsCategory == null)
            {
                return NotFound();
            }
            return View(newsCategory);
        }

        // POST: NewsCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NewsCategoryID,Name")] NewsCategory newsCategory)
        {
            if (id != newsCategory.NewsCategoryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(newsCategory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsCategoryExists(newsCategory.NewsCategoryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(newsCategory);
        }

        // GET: NewsCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsCategory = await _context.NewsCategory
                .FirstOrDefaultAsync(m => m.NewsCategoryID == id);
            if (newsCategory == null)
            {
                return NotFound();
            }

            return View(newsCategory);
        }

        // POST: NewsCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var newsCategory = await _context.NewsCategory.FindAsync(id);
            _context.NewsCategory.Remove(newsCategory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewsCategoryExists(int id)
        {
            return _context.NewsCategory.Any(e => e.NewsCategoryID == id);
        }
    }
}

OnlineNewspaper/OnlineNewspaper/Controllers/NewsDetailsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using OnlineNewspaper.Data;
using OnlineNewspaper.Models;

namespace OnlineNewspaper.Controllers
{
    public class NewsDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IFileProvider fileProvider;
        private readonly IHostingEnvironment hostingEnvironment;


        public NewsDetailsController(ApplicationDbContext context,
                          IFileProvider fileprovider, IHostingEnvironment env)
        {
            _context = context;
            fileProvider = fileprovider;
            hostingEnvironment = env;
        }

        // GET: NewsDetails
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.NewsDetails.Include(n => n.NewsCategory);
            return View(await applicationDbContext.ToListAsync());
        }


        public async Task<IActionResult> ManageNews()
        {
            var applicationDbContext = _context.NewsDetails.Include(n => n.NewsCategory);
            return View(await applicationDbContext.ToListAsync());
        }


        [HttpGet]
        public async Task<IActionResult> NationalNews()
        {
            var national = from n in _context.NewsDetails select n;
            national = national.Where(s => s.NewsCategoryID == 5);
            return View(await national.ToListAsync());
        }


        [HttpGet]
        public async Task<IActionResult> Sports()
        {
            var national = from n in _context.NewsDetails select n;
            national = national.Where(s => s.NewsCategoryID == 3);
            return View(await national.ToListAsync());
        }


        [HttpGet]
        public async Task<IActionResult> International()
        {
            var national = from n in _context.NewsDetails select n;
            national = national.Where(s => s.NewsCategoryID == 4);
            return View(await national.ToListAsync());
        }


        // GET: NewsDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsDetails = await _context.NewsDetails
                .Include(n => n.NewsCategory)
                .FirstOrDefaultAsync(m => m.NewsDetailsID == id);
            if (newsDetails == null)
            {
                return NotFound();
            }

            return View(newsDetails);
        }


        [Authorize(Roles ="Admin")]
        // GET: NewsDetails/Create
        public IActionResult Create()
        {
            ViewData["NewsCategoryID"] = new SelectList(_context.NewsCategory, "NewsCategoryID", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NewsDetails newsDetails , IFormFile file)
        {
            if (ModelState.IsValid)
            {
                _context.Add(newsDetails);
                await _context.SaveChangesAsync();

                // Code to upload image if not null
                if (file != null || file.Length != 0)
                {
                    // Create a File Info 
                    FileInfo fi = new FileInfo(file.FileName);

                    // This code creates a unique file name to prevent duplications 
                    // stored at the file location
                    var newFilename = newsDetails.NewsDetailsID + "_" + String.Format("{0:d}",
                                      (DateTime.Now.Ticks / 10) % 100000000) + fi.Extension;
                    var webPath = hostingEnvironment.WebRootPath;
                    var path = Path.Combine("", webPath + @"\ImageFiles\" + newFilename);

                    // IMPORTANT: The pathToSave variable will be save on the column in the database
                    var pathToSave = @"/ImageFiles/" + newFilename;

                    // This stream the physical file to the allocate wwwroot/ImageFiles folder
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    // This save the path to the record
                    newsDetails.Image = pathToSave;
                    _context.Update(newsDetails);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(newsDetails);
        }





        // GET: NewsDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsDetails = await _context.NewsDetails.FindAsync(id);
            if (newsDetails == null)
            {
                return NotFound();
            }
            ViewData["NewsCategoryID"] = new SelectList(_context.NewsCategory, "NewsCategoryID", "NewsCategoryID", newsDetails.NewsCategoryID);
            return View(newsDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, NewsDetails newsDetails)
        {
            if (id != newsDetails.NewsDetailsID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(newsDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsDetailsExists(newsDetails.NewsDetailsID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NewsCategoryID"] = new SelectList(_context.NewsCategory, "NewsCategoryID", "NewsCategoryID", newsDetails.NewsCategoryID);
            return View(newsDetails);
        }

        // GET: NewsDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsDetails = await _context.NewsDetails
                .Include(n => n.NewsCategory)
                .FirstOrDefaultAsync(m => m.NewsDetailsID == id);
            if (newsDetails == null)
            {
                return NotFound();
            }

            return View(newsDetails);
        }

        // POST: NewsDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var newsDetails = await _context.NewsDetails.FindAsync(id);
            _context.NewsDetails.Remove(newsDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewsDetailsExists(int id)
        {
            return _context.NewsDetails.Any(e => e.NewsDetailsID == id);
        }
    }
}

OnlineNewspaper/OnlineNewspaper/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomIdentity_Core</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="NewsDetails" asp-action="Index" style="font-size:30px; font-weight:bold">সংবাদ প্রতিদিন</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @await Html.PartialAsync("_LoginPartial")
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewsDetails" asp-action="NationalNews">বাংলাদেশ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewsDetails" asp-action="International">আন্তর্জাতিক</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewsDetails" asp-action="Sports">খেলা</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="#" asp-action="#">বিনোদন</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="#" asp-action="#">বিজ্ঞান ও প্রযুক্তি</a>
                        </li>
                    </ul>

                </div>

            </div>
        </nav>
    </header>


    <div class="text-center" style="background-color:aquamarine">
        <h1 class="display-4">স্বাগতম অ্যাডমিন </h1>
    </div>
    <div id="Container">
        <div id="SideBar" style=" min-height:20px; " >

            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="padding-left:90px">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="float:left">
                            <a style="border-radius:30px; padding:3px" class="nav-item btn-success" asp-area="" asp-controller="NewsDetails" asp-action="Create">সংবাদ যুক্ত করুন</a>
                        </li>
                        <li class="nav-item" style="float:left">
                            <a style="border-radius:30px; padding:3px" class="nav-item btn-success" asp-area="" asp-controller="NewsCategories" asp-action="Create">ক্যাটাগরি যুক্ত করুন</a>
                        </li>
                        <li class="nav-item" style="float:left">
                            <a style="border-radius:30px; padding:3px" class="nav-item btn-success" asp-area="" asp-controller="NewsCategories" asp-action="Index">ক্যাটাগরি এর তালিকা </a>
                        </li>
                        <li class="nav-item" style="float:left">
                            <a style="border-radius:30px; padding:3px" class="nav-item btn-success" asp-area="" asp-controller="NewsDetails" asp-action="ManageNews">সংবাদ ম্যানেজ  করুন</a>
                        </li>
                    </ul>
                </nav>             
            </form>
        </div>
        <div id="Content" style=" min-height:500px; width:100%;  padding-left: 90px">
            @RenderBody()
        </div>
    </div>
    

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - CustomIdentity_Core - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

OnlineNewspaper/OnlineNewspaper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomIdentity_Core</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="NewsDetails" asp-action="Index" style="font-size:30px; font-weight:bold">সংবাদ প্রতিদিন</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @await Html.PartialAsync("_LoginPartial")
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewsDetails" asp-action="NationalNews">বাংলাদেশ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewsDetails" asp-action="International">আন্তর্জাতিক</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewsDetails" asp-action="Sports">খেলা</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="#" asp-action="#">বিনোদন</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="#" asp-action="#">বিজ্ঞান ও প্রযুক্তি</a>
                        </li>
                    </ul>

                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            <h5>Location: Chittagong @DateTime.Now.ToLongDateString()</h5>

            @RenderBody()
        </main>
    </div>
    <br />    <br />    <br />    <br />    <br />    <br />    <br />    <br />    <br />    <br />    <br />    <br /><hr /><hr />
    <div style="height:300px; background-color:darkgrey;">
        <footer>
            <div class="container">
                &copy; 2019 - CustomIdentity_Core - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>



    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>

</html>